<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <h1>Principio de abierto_cerrado</h1>
    <b>"Los objetos o entidades deberían estar abiertas a su extensión, pero cerradas para su modificación"</b>
    <br>
    <b>Por ejemplo:</b>
    <p>Tenemos las siguientes figuras:</p>
    <p>Clase Circulo</p>
    <img src="../img/ocp.png" alt="">
    <p>Clase Rectangulo</p>
    <img src="../img/ocp_1.png" alt="">
    <p>Clase Triangulo</p>
    <img src="../img/ocp_3.png" alt="">
    <p>Una clase abstracta donde creamos un merodo para que puedan heredar las clas figuras</p>

    <img src="../img/ocp_4.png" alt="">
    <p>Creamos los objetos de cada clase de figuras con sus respectivos parametros </p>
    <img src="../img/ocp_5.png" alt="">
</body>

</html>