<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="../css/sistema/style.css" type="text/css">
</head>

<body>
    <h1>PRINCIPIOS SOLID</h1>
    <div class="btn-group" role="group" aria-label="Basic mixed styles example">
        <a href="../sistema/responsabilidadUnica" type="button" class="btn btn-danger">Principio de responsabilidad unica</a>
        <a href="../sistema/abiertoCerrado" type="button" class="btn btn-warning">Principio de cerrado abierto</a>
        <a href="../sistema/sustitucionLiskov" type="button" class="btn btn-success">Princicio susctitucio de Liskov</a>
        <a href="../sistema/segregacionInterface" type="button" class="btn btn-primary">Principio segregacion de interface</a>
        <a href="../sistema/invercionDependencia" type="button" class="btn btn-dark">principio invercion de dependencia</a>
    </div>
    <p>Es un acrónimo de los cinco principios del diseño orientado a objetos (OOD Object Oriented Design) creados por Uncle Bob, quien también es coautor de los principios del desarrollo web agile.</p>
    <img src="../img/solid.jpg" alt="">


</body>

</html>