<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <h1>Principio de invercion de dependencia</h1>
    <p>Las entidades deben depender de abstracciones no de concreciones. 
    El módulo de alto nivel no debe depender del módulo de bajo nivel, 
    pero deben depender de abstracciones.</p>
</body>

</html>