<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <h1>Principio de responsabilidad unica</h1>
    <p>Una clase sólo debe tener un motivo para cambiar, lo que significa que sólo debe tener una tarea.</p>
<p>Por ejemplo:</p>

</body>

</html>