<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <h1>Principio de segregacion de interface</h1>
    <b>"Una clase nunca debe ser forzada a implementar una interface
        que no usa, empleando métodos que no tiene por qué usar."</b>
    <br>
    <b>Por ejemplo</b>
    <p>Tenemo la clase animal donde tiene la propiedad tipo de animal</p>
    <img src="../img/isp.png" alt="">
    <p>Tenemos la interface caminar</p>
    <img src="../img/isp_2.png" alt="">
    <p>Tenemos la interface cazar </p>
    <img src="../img/isp_3.png" alt="">
    <p>Tenemos la Interface correr</p>
    <img src="../img/isp_4.png" alt="">
    <p>Tenemos la clase leon que implemeta las interfaces de caminar, cazar y correr</p>
    <img src="../img/isp_5.png" alt="">
    <p>Tenemos la clase tortuga que solo implemeta la clase caminar</p>
    <img src="../img/isp_6.png" alt="">
</body>

</html>