<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <h1>Principio de segregacion de interface</h1>
    <p>Una clase nunca debe ser forzada a implementar una interface 
    que no usa, empleando métodos que no tiene por qué usar.</p>
</body>

</html>