<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <h1>Principio de sustitucion de liskov</h1>
    <p>Si S es una subclase de T, entonces los objetos de T podrían ser 
    substituidos por objetos del tipo S sin alterar las propiedades del 
    problema. Esto es, cada clase que hereda de otra puede usarse como su 
    padre sin necesidad de conocer las diferencias entre ellas.</p>
</body>

</html>