<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="../home/inicio">Tu Enciclopedia</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDarkDropdown" aria-controls="navbarNavDarkDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="../sistema/index"">Area desarrollo de sistemas</a>
                </li>
                </lu>
        </div>
        <div class=" collapse navbar-collapse" id="navbarNavDarkDropdown">
                        <ul class="navbar-nav">
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Area de apuestas
                                </a>
                                <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
                                    <li><a class="dropdown-item" href="../apuesta/esperanzaMatematica"">Esperanza matematica</a></li>
                                    <li><a class=" dropdown-item" href="../apuesta/pca">Probabilidad de la casa apuesta(PCA)</a></li>
                                    <li><a class="dropdown-item" href="../apuesta/gananciaNeta">Ganancia neta</a></li>
                                    <li><a class="dropdown-item" href="../apuesta/roi/">Retorno de inversion(ROI)</a></li>
                                </ul>
                            </li>
                        </ul>
        </div>
    </div>
</nav>