<!-- <div class="card mb-3" style="max-width: 540px;">
    <div class="row g-0">
        <div class="col-md-4">
            <img src="../img/sistema.png" alt="...">
        </div>
        <div class="col-md-8">
            <div class="card-body">
                <h5 class="card-title">Area desarrollo de sistemas</h5>
                <p class="card-text">En términos más generales, el área de sistemas se encarga de la red informática que interconecta a la empresa, las computadoras que están a disposición de los usuarios y/o que prestan servicios a las computadoras personales, asi como de las aplicaciones y programas instalados en ellas y los servicios de uso general </p>
                <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
            </div>
        </div>
    </div>
</div>
<div class="card mb-3" style="max-width: 540px;">
    <div class="row g-0">
        <div class="col-md-4">
            <img src="../img/apuesta.png" alt="...">
        </div>
        <div class="col-md-8">
            <div class="card-body">
                <h5 class="card-title">Area de apuestas</h5>
                <p class="card-text">Consideramos que Bet365 se posiciona hoy
                    como la mejor casa de apuestas. Tanto por su selección de apuestas
                    pre-partido y en directo, como por la cantidad de funciones especiales
                    ue pone a disposición de sus clientes: retransmisión de deportes de todo tipo en su web,
                    así como funciones como crear apuesta o cashout.</p>
                <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
            </div>
        </div>
    </div>
</div> -->

<div class="row">
    <div class="row row-cols-1 row-cols-md-2 g-4">
        <div class="col">
            <div class="card">
                <img src="../img/sistema.png" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">Area de desarrollo de sistemas</h5>
                    <p class="card-text">Detectar las necesidades de proceso de datos e información de la Organización y proponer las soluciones informáticas pertinentes.
                        Establecer conjuntamente con las áreas usuarias, las especificaciones técnicas y enlaces de los proyectos y sistemas, que apoyen el mejoramiento continuo de las funciones sustantivas de la Organización.
                        </p>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="card">
                <img src="../img/apuesta.png"" class=" card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">Area de apuestas</h5>
                    <p class="card-text">Consideramos que Tinka se posiciona hoy
                        como la mejor casa de apuestas. Tanto por su selección de apuestas
                        pre-partido y en directo, como por la cantidad de funciones especiales
                        ue pone a disposición de sus clientes: retransmisión de deportes de todo tipo en su web,
                        así como funciones como crear apuesta o cashout.</p>
                </div>
            </div>
        </div>
    </div>
</div>