 <div class="container">
     <div class="row">
         <div class="col-sm-12">
             <h1>Esperanza matematica</h1>
             <b>Es una forma de medir si a largo plazo una apuesta será beneficiosa
                 o no para el jugador. Si la Esperanza Matemática es menor que 1 el juego es “desfavorable
                 para el apostador” en caso contrario el juego es “favorable para el apostador”</b>
         </div>
     </div>
     <div class="row">
         <div class="col-sm-6">
             <br>

             <img src="../img/esperanza.png" alt="">
         </div>
         <div class="col-sm-6">
             <br>
             <br>
             <form action="<?= URL ?>apuesta/esperanzaMatematica" method="POST">
                 <div class="form-group">
                     <label for="">Cuota:</label>
                     <input type="numbert" id="" name="cuota" class="form-control" value="<?= $data['cuota'] ?>" step="1" required>
                 </div>
                 <div class="form-group">
                     <label for="">Probabilidad:</label>
                     <input type="numbert" id="" name="probabilidad" class="form-control" value="<?= $data['probabilidad'] ?>" step="1" required>
                 </div>
                 <br>
                 <div class="form-group">
                     <button type="submit" class="btn btn-primary">Enviar</button>
                 </div>
                 <div class="form-group">
                     Respuesta: <label>Esperanza matematica </label>
                     <input type="text" class="form-control" value=" <?= $data['esperanza'] ?>" disabled>
                 </div>
             </form>
         </div>
     </div>

 </div>