 <div class="container">
     <div class="row">
         <div class="col-sm-8">
             <h1>Retorno de inversion(ROI)</h1>
             <b>Retorno de inversión es una métrica que nos indica cuánto dinero genera nuestro dinero
                 apostado.</b>
             <b></b>
         </div>
     </div>
     <div class="row">
         <div class="col-sm-8">
             <form action="<?= URL ?>apuesta/roi" method="POST">
                 <div class="form-group">
                     <label for="">Apuesta:</label>
                     <input type="apuesta" id="apuesta" name="apuesta" class="form-control" value="<?= $data['apuesta'] ?>">
                 </div>
                 <div class="form-group">
                     <label for="">Cuota:</label>
                     <input type="numeric" id="cuota" name="cuota" class="form-control" value="<?= $data['cuota'] ?>">
                 </div>
                 <br>
                 <div class="form-group">
                     <button type="submit" class="btn btn-primary">Calcular</button>
                 </div>
                 <div class="col-sm-8">
                     Resultado: <label>ganancia neta </label>
                     <input type="text" class="form-control" value=" <?= $data['neta'] ?>" disabled>
                 </div>

                 <div class="form-group">
                     <label for="">Inversion:</label>
                     <input type="inversion" id="" name="inversion" class="form-control" value="<?= $data['inversion'] ?>">
                 </div>
                 <br>
                 <div class="form-group">
                     <button type="submit" class="btn btn-primary">Calcular</button>
                 </div>
             </form>
         </div>
     </div>
     <div class="row">
         <div class="col-sm-8">
             Resultado: <label>retorno de inversion </label>
             <input type="text" class="form-control" value=" <?= $data['roi'] ?>" disabled>
         </div>
     </div>
 </div>